name: github-stats

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: stats
      - name: Generate stats SVG
        uses: cicirello/user-statistician@v1
        with:
          image-file: images/stats.svg
          theme: light
          locale: en
        env:
          GITHUB_TOKEN: ${{ secrets.STATS_PAT }}
